M48
; DRILL file {KiCad (6.0.5)} date Sat May 28 08:22:10 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-28T08:22:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X7.899Y-5.2681
X7.899Y-5.5359
T2
X3.573Y-5.836
X3.593Y-3.926
X7.424Y-3.894
X7.845Y-5.865
T0
M30
