M48
; DRILL file {KiCad 7.0.1} date Fri Jun  9 14:16:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-09T14:16:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X7.899Y-5.2681
X7.899Y-5.5359
T2
X3.573Y-5.836
X3.593Y-3.926
X7.424Y-3.894
X7.845Y-5.865
T0
M30
